/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tickets;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ed
 */
public class BookingsFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookingsFrame
     */
    public BookingsFrame() {
        initComponents();
        rcptasd.setEditable(false);
        
        String url = "jdbc:mysql://sql479.main-hosting.eu:3306/u663917405_movie_ticketin";
        String username = "u663917405_movie_ticketin";
        String password = "Gq9K9sKvjWc7BMT!";
        
        try{
            Connection con = DriverManager.getConnection(url, username, password);
            String query = "SELECT * FROM bookings order by id";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                String gettype = rs.getString("rcpt_no");
                
                recpas.addItem(gettype.toUpperCase());

            }
            
            st.close(); 
            
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recpas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        rcptasd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKINGS DATA");

        recpas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        recpas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT A RECEIPT" }));
        recpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recpasActionPerformed(evt);
            }
        });

        rcptasd.setColumns(20);
        rcptasd.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        rcptasd.setRows(5);
        jScrollPane1.setViewportView(rcptasd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(recpas, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(recpas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recpasActionPerformed
        
        String url = "jdbc:mysql://sql479.main-hosting.eu:3306/u663917405_movie_ticketin";
        String username = "u663917405_movie_ticketin";
        String password = "Gq9K9sKvjWc7BMT!";
        
        try{
            Connection con = DriverManager.getConnection(url, username, password);
            String query = "SELECT * FROM bookings where rcpt_no = '"+recpas.getSelectedItem().toString()+"' ";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                
                rcptasd.setText("*********R E C E I P T*********\n" +
"\n" +
"    MOVIE TICKETING ONLINE\n" +
"\n" +
"M.J. Cuenco Ave, Cor R. Palma Street, 6000 Cebu\n" +
"\n" +
"Date ---         "+rs.getString("created_at")+"\n" +
"Rcpt no ---      "+rs.getString("rcpt_no")+"\n" +
"Tckt no ---      "+rs.getString("tckt_no")+"\n" +
"Cstmr ---        "+rs.getString("username")+"\n" +
"-------------------------------\n" +
"\n" +
"CINEMA TYPE ---  "+rs.getString("cinema_type")+"\n" +
"\n" +
"MOVIE NAME ---   "+rs.getString("movie_name")+"\n" +
"\n" +
"SEAT NO ---      "+rs.getString("seat_no")+"\n" +
"\n" +
"BOOKING DATE & TIME ---    "+rs.getString("date_time")+"\n" +
"\n" +
"TOTAL ---             "+rs.getString("total")+"\n" +
"\n" +
"-------------------------------\n" +
"THIS RECEIPT WILL SERVE AS YOUR\n" +
"MOVIE TICKET. DO NOT THROW AWAY!!\n" +
"-------------------------------\n" +
" MOVIE TICKETING OFFICIAL RECEIPT\n" +
"-------------------------------");

            }
            
            st.close(); 
            
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_recpasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea rcptasd;
    private javax.swing.JComboBox<String> recpas;
    // End of variables declaration//GEN-END:variables
}
